#!/bin/sh -ex

# download, build and install openvas from source using overlay script
/usr/local/bin/turnkey-openvas-src-install

# run OpenVAS setup
openvas-setup

# set admin initial password for build
/usr/sbin/openvasmd --user="admin" --new-password="turnkey"

# create TurnKey Default port_list
cat /tmp/create_turnkey_default_port_list.xml | omp -u admin -w turnkey -iX "-"

# create TurnKey scan_config
cat /tmp/create_turnkey_scan_config.xml | omp -u admin -w turnkey -iX "-"

# cleanup
rm -f /tmp/create_turnkey_*

# listen on 0.0.0.0
sed -i 's/127.0.0.1/0.0.0.0/g' /lib/systemd/system/greenbone-security-assistant.service /lib/systemd/system/openvas-manager.service /lib/systemd/system/openvas-scanner.service

# start OpenVAS on initial boot
sed -i "/Default-Start/ s/:.*$/:     2 3 4 5/" /etc/init.d/greenbone-security-assistant /etc/init.d/openvas-manager /etc/init.d/openvas-scanner

update-rc.d openvas-scanner remove
systemctl enable openvas-scanner.service
update-rc.d openvas-manager remove
systemctl enable openvas-manager.service
update-rc.d greenbone-security-assistant remove
systemctl enable greenbone-security-assistant

# update OpenVAS feeds via crontab
cat << EOF  >> /etc/crontab
# update openvas feeds
25 1    * * *   root    /usr/local/bin/update-openvas >/dev/null 2>&1
#
EOF

# stop OpenVAS
service greenbone-security-assistant stop
service openvas-manager stop
service openvas-scanner stop

